<?php
/**
* @date 11/12/2015
* @author Emmanuel Palomeque Alcazar <epalomeque@gmail.com>
*
**/

// Implementa hook_menu()
function smumm_menu(){
    // Menu de Administración
  $items['admin/structure/structure/supahmegaultramegamenu'] = array(
    'title' => t('Configuración de smumm (SupahMegaUltraMegaMenu)'),
    'description' => t('Configurar el módulo SMUMM'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('smumm_admin'),
    'access arguments' => array('administer smumm settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

// Implementa hook_block_info()
function smum_block_info() {
    $blocks['bloque_smumm_menufront'] = array(
    // Título del bloque en la configuración del administrador 
    'info' => t('Menu SMUMM'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

// Implementa hook_block_view()
function smumm_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'bloque_smumm_menufront':
      // Título del bloque.
      $block['subject'] = t('Boton Editar');
      // Función que retorna el contenido o función que se quiere en el bloque.
      $block['content'] = smumm_boton_editar();
      break;
    }
    return $block;
}

// Implementa funcion hook_boton_editar()
function smumm_boton_editar() {
  global $user;
  $user_uid = $user->uid;
  return l(t('Editar Cuenta'), "user/$user_uid/edit");
}
