<?php
/**
* @date 11/12/2015
* @author Emmanuel Palomeque Alcazar <epalomeque@gmail.com>
*
**/

include 'smumm-implements-block.inc';

// Implementa hook_menu()
function smumm_menu(){
    // Menu de Administración
  $items['admin/structure/structure/supahmegaultramegamenu'] = array(
    'title' => t('Configuración de smumm (SupahMegaUltraMegaMenu)'),
    'description' => t('Configurar el módulo SMUMM'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('smumm_admin'),
    'access arguments' => array('administer smumm settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function smumm_admin ($form, &$form_state) {
  $los_menus = menu_get_menus(TRUE);
  print_r($los_menus);

  $form = array();

  $form['smumm_departamento'] = array (
    '#title' => t('Departamento'),
    '#type' => 'fieldset',
    '#description' => t('Ingresa los datos del departamento de atención'),
    '#collapsible' => TRUE,
    );

  return system_settings_form($form);
}

function smumm_admin_submit($form , &$form_state){
  }

/**
* Implements hook_permission().
*/
function smumm_permission() {
  return array(
  'administer consulta_padron_proveedores settings' => array(
  'title' => t('Administer smumm configurations'),
  'restrict access' => true,
  )
  );
  }